// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Prisma 7's runtime honors directUrl for migrations/introspection, but
    // the @prisma/config Datasource type only declares { url, shadowDatabaseUrl }.
    // Cast via `as any` so TypeScript accepts the known-good runtime field.
    directUrl: process.env["DIRECT_URL"],
  } as any,
});
